# (Optional) PagesCMS configuration.
# This is NOT required for GitHub Pages deployment.
#
# More on: https://pagescms.org/docs/configuration/

media:
  - name: assets
    label: Assets
    input: src/assets
    output: ../../assets
    categories: [image, document]

content:
  - name: blog
    label: Posts
    type: collection
    path: src/content/blog
    filename: '{year}-{month}-{day}-{primary}.md'
    view:
      fields: [title, pubDate, updatedDate, author, tags]
      sort: [pubDate, title]
      default:
        sort: pubDate
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: pubDate
        label: Published
        type: date
        required: true
      - name: heroImage
        label: Hero image
        type: image
      - name: author
        label: Author
        type: string
      - name: tags
        label: Tags
        type: string
        list: true

  - name: projects
    label: Projects
    type: collection
    path: src/content/projects
    filename: '{primary}.md'
    view:
      fields: [title, pubDate, updatedDate]
      sort: [pubDate]
      default:
        sort: pubDate
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: pubDate
        label: Published
        type: date
        required: true
      - name: updatedDate
        label: Updated
        type: date
      - name: heroImage
        label: Hero image
        type: image

